apiVersion: v1
kind: Pod
metadata:
  name: spring
  # namespace: dev
  labels:
    app: spring

spec:
  containers:
  - name: spring
    image: mahmom/gs-spring-boot-docker:v1.0 
    ports:
    - containerPort: 3306
    env:
    - name: MY_SQL_DB_NAME
      valueFrom:
        configMapKeyRef:
          name: spring
          key: dbName 
    - name: MY_SQL_user_NAME
      valueFrom:
        configMapKeyRef:
          name: spring
          key: userName  

    - name: MY_SQL_password
      valueFrom:
        configMapKeyRef:
          name: spring
          key: password